name: 'Setup GAP for package testing'
description: 'Download and compile CI scripts, GAP and its packages'
inputs:
  GAP_PKGS_TO_CLONE:
    description: 'the GAP packages to clone'
    required: false
    default: ''
  GAP_PKGS_TO_DOWNLOAD:
    description: 'the GAP packages to download, specify a full URL pointing to a zip, tar.bz2 or tar.gz file to download and unpack' 
    required: false 
    default: ''
  GAP_PKGS_TO_BUILD:
    description: 'the GAP packages to build'
    required: false
    default: ''

runs:
  using: "composite"
  steps:  
      - name: "Clone additional GAP packages"
        shell: bash
        run: |
          # optionally: clone specific package versions, in case we need to test
          # with development versions
          cd ${GAP_HOME}/pkg
          for pkg in ${{ inputs.GAP_PKGS_TO_CLONE }}; do
              # delete any existing variants of the package to avoid multiple versions
              # from being compiled later on
              rm -rf "$pkg"*
              if [[ "$pkg" =~ ^http ]] ; then
                  # looks like a full URL
                  git clone "$pkg"
              elif [[ "$pkg" =~ ^[^/]+/[^/]+$ ]] ; then
                  # looks like ORG/REPO
                  git clone https://github.com/"$pkg"
              elif [[ "$pkg" =~ ^[^/]+$ ]] ; then
                  # looks like just a REPO name
                  git clone https://github.com/gap-packages/"$pkg"
              else
                  echo "Invalid package name or URL '$pkg' in GAP_PKGS_TO_CLONE"
                  exit 1
              fi
          done

      - name: "Download additional GAP Packages"
        shell: bash
        run: |
          # optionally: download published versions of packages
          cd ${GAP_HOME}/pkg
          for pkg in ${{ inputs.GAP_PKGS_TO_DOWNLOAD }}; do
              # delete any existing variants of the package to avoid multiple versions
              # from being compiled later on
              archive=${pkg##*/}
              pkgname=${archive%%-*}
              rm -rf "$pkgname"*
              if [[ "$pkg" =~ (.tar.gz|.tar.bz2)$ ]] ; then
                  wget ${pkg}
                  tar -xvf ${archive}
              elif [[ "$pkg" =~ .zip$ ]] ; then
                  wget ${pkg}
                  unzip ${archive}
              else
                  echo "Invalid URL in GAP_PKGS_TO_DOWNLOAD"
                  exit 1
              fi
          done
          
      - name: "Build additional GAP packages"
        shell:  bash
        run: |
          # build some packages
          BuildPackagesOptions="--strict"
          cd ${GAP_HOME}/pkg
          for pkg in ${{inputs.GAP_PKGS_TO_BUILD}}; do
              ../bin/BuildPackages.sh ${BuildPackagesOptions} $pkg*
          done
