name: CI

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  test:
    name: ${{ matrix.container }} - Packages - ${{ matrix.GAP_PKGS_TO_BUILD }} - ${{ matrix.GAP_PKGS_TO_CLONE }} - ${{ matrix.GAP_PKGS_TO_DOWNLOAD }} - ${{ matrix.os }} 
    runs-on: ${{ matrix.os }} 
    container:
      image: ghcr.io/wucas/${{ matrix.container }}:latest
      ##options: --user root
    # Don't run this twice on PRs for branches pushed to the same repository
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        container: [gap-4.11.1-minimal]
        GAP_PKGS_TO_BUILD:
          - ''
        GAP_PKGS_TO_CLONE:
          - ''
        GAP_PKGS_TO_DOWNLOAD:
          - ''
        include:
          - os: ubuntu-latest
            container: 'gap-4.11.1-minimal'
            GAP_PKGS_TO_BUILD: 'io'
            GAP_PKGS_TO_CLONE: 'recog io'
            GAP_PKGS_TO_DOWNLOAD: 'http://www.math.rwth-aachen.de/homes/Thomas.Breuer/atlasrep/atlasrep-2.1.2.tar.gz'
          - os: ubuntu-latest
            container: 'gap-4.11.1-minimal'
            GAP_PKGS_TO_BUILD: 'CddInterface'
            GAP_PKGS_TO_CLONE: 'homalg-project/CddInterface'
            GAP_PKGS_TO_DOWNLOAD: ''
          - os: ubuntu-latest
            container: 'gap-4.11.1-minimal'
            GAP_PKGS_TO_BUILD: 'xgap'
            GAP_PKGS_TO_CLONE: 'xgap'
            GAP_PKGS_TO_DOWNLOAD: ''
#          - os: macos-latest
#            gap-branch: master
#            GAP_PKGS_TO_BUILD: ''
#            HPCGAP: no

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      #- if: ${{ matrix.os == 'windows-latest' }}
      #  uses: gap-actions/setup-cygwin@v1
      - name: "run action"
        uses: ./
        with:
          GAP_PKGS_TO_BUILD: ${{ matrix.GAP_PKGS_TO_BUILD }}
          GAP_PKGS_TO_CLONE: ${{ matrix.GAP_PKGS_TO_CLONE }}
          GAP_PKGS_TO_DOWNLOAD: ${{ matrix.GAP_PKGS_TO_DOWNLOAD }}
      - name: "echo fail.log"
        shell: bash
        run: |
          if [[ -f /home/gap/inst/gap-4.11.1/pkg/log/fail.log ]] ; then
            cat /home/gap/inst/gap-4.11.1/pkg/log/fail.log
          fi
          echo cat /home/gap/inst/gap-4.11.1/pkg/log/fail.log | wc -l
#          if [[  ]] ; then
#
#          fi
