name: CI

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  test:
    name: ${{ matrix.gap-branch }} - Packages ${{ matrix.GAP_PKGS_TO_BUILD }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    container:
      image: ghcr.io/wucas/${{ matrix.container }}
      ##options: --user root
    # Don't run this twice on PRs for branches pushed to the same repository
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        container: [gap-4.11.1-minimal]
        GAP_PKGS_TO_BUILD:
          - ''
        GAP_PKGS_TO_CLONE:
          - ''
        GAP_PKGS_TO_DOWNLOAD:
          - ''
        include:
          - os: ubuntu-latest
            container: [gap-4.11.1-minimal]
            GAP_PKGS_TO_BUILD: ''
            GAP_PKGS_TO_CLONE: 'recog'
            GAP_PKGS_TO_DOWNLOAD: 'http://www.math.rwth-aachen.de/homes/Thomas.Breuer/atlasrep/atlasrep-2.1.2.tar.gz'
#          - os: ubuntu-latest
#            gap-branch: master
#            GAP_PKGS_TO_BUILD: ''
#            HPCGAP: yes
#          - os: ubuntu-latest
#            gap-branch: master
#            ABI: 32
#            GAP_PKGS_TO_BUILD: 'default'
#            HPCGAP: no
#          - os: macos-latest
#            gap-branch: master
#            GAP_PKGS_TO_BUILD: ''
#            HPCGAP: no

    steps:
      - uses: actions/checkout@v3
      #- if: ${{ matrix.os == 'windows-latest' }}
      #  uses: gap-actions/setup-cygwin@v1
      - uses: ./
        with:
          GAP_PKGS_TO_BUILD: ${{ matrix.GAP_PKGS_TO_BUILD }}
          GAP_PKGS_TO_CLONE: ${{ matrix.GAP_PKGS_TO_CLONE }}
          GAP_PKGS_TO_DOWNLOAD: ${{ matrix.GAP_PKGS_TO_DOWNLOAD }}
